import { create } from 'zustand';
import { persist } from 'zustand/middleware';

export interface SavedAnalysis {
    id: string;
    timestamp: string;
    featureId: string;
    featureName: string;
    featureType: 'trail-damage-points' | 'timber-plots-points' | 'burn-severity-fill';
    coordinates: [number, number];
    fireContext: string;
    selectedChipIds: string[];
    userQuery: string;
    result: string;
}

interface AnalysisHistoryState {
    analyses: SavedAnalysis[];

    // Actions
    saveAnalysis: (analysis: Omit<SavedAnalysis, 'id' | 'timestamp'>) => string;
    deleteAnalysis: (id: string) => void;
    getAnalysis: (id: string) => SavedAnalysis | undefined;
    clearHistory: () => void;
}

export const useAnalysisHistoryStore = create<AnalysisHistoryState>()(
    persist(
        (set, get) => ({
            analyses: [],

            saveAnalysis: (analysis) => {
                const id = `analysis-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`;
                const newAnalysis: SavedAnalysis = {
                    ...analysis,
                    id,
                    timestamp: new Date().toISOString(),
                };

                set((state) => ({
                    analyses: [newAnalysis, ...state.analyses], // Newest first
                }));

                console.log('[AnalysisHistory] Saved analysis:', id);
                return id;
            },

            deleteAnalysis: (id) => {
                set((state) => ({
                    analyses: state.analyses.filter((a) => a.id !== id),
                }));
                console.log('[AnalysisHistory] Deleted analysis:', id);
            },

            getAnalysis: (id) => {
                return get().analyses.find((a) => a.id === id);
            },

            clearHistory: () => {
                set({ analyses: [] });
                console.log('[AnalysisHistory] Cleared all analyses');
            },
        }),
        {
            name: 'ranger-analysis-history', // localStorage key
            version: 1,
        }
    )
);

/**
 * Generate a downloadable markdown file from an analysis
 */
export function downloadAnalysisAsMarkdown(analysis: SavedAnalysis): void {
    const date = new Date(analysis.timestamp);
    const filename = `site-analysis-${analysis.featureName.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase()}-${date.toISOString().slice(0, 10)}.md`;

    const content = `# Site Analysis Report

**Feature:** ${analysis.featureName}
**Type:** ${analysis.featureType}
**Coordinates:** ${analysis.coordinates[1].toFixed(4)}°N, ${Math.abs(analysis.coordinates[0]).toFixed(4)}°W
**Fire Context:** ${analysis.fireContext}
**Analysis Date:** ${date.toLocaleDateString()} ${date.toLocaleTimeString()}

---

${analysis.result}

---

*Generated by RANGER Command Console*
`;

    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    console.log('[AnalysisHistory] Downloaded:', filename);
}
